[package]
name = "Proyecto_1"
version = "0.1.0"
edition = "2024"

[dependencies]
serde       = { version = "1", features = ["derive"] }   # para JSON (/status)
serde_json  = "1"                                        # para serializar JSON
sha2        = "0.10"                                     # para SHA-256
hex         = "0.4"                                      # para codificar SHA
rand        = "0.8"                                      # para /random
chrono      = { version = "0.4", features = ["serde"] } # para /timestamp
url         = "2"                                        # parseo de query params